{
  "hash": "5eeb410bc74efbf7465fd4778bf7a25c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 05\"\nsubtitle: \"This exercise is a hands-on guide for Global Measures and Local Measures of Spatial Autocorrelation\"\nauthor: \"Hung Thai\"\ndate: \"Sep 23, 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true\n  eval: true\n  mesage: false\n  warning: false\n  freeze: true\nformat: \n  html:\n    toc: true\n    toc-depth: 4\n    code-copy: true\neditor: visual\n---\n\n# 5.1 Global Measures of Spatial Autocorrelation\n\n## 5.1.1 Overview\n\nThis hands-on exercise will show how to compute Global Measures of Spatial Autocorrelation (GMSA) by using **spdep** package.\n\n::: callout-note\nreference:\n\n\\[r4gdsa Chapter 09: Global Measures of Spatial Autocorrelation\\](<https://r4gdsa.netlify.app/chap09.html>)\n:::\n\nA key goal of spatial policy is ensuring balanced regional development. This study utilizes spatial statistics to evaluate geographic equity by addressing three consecutive questions:\n\n1.  Is provincial development distributed evenly?\n\n2.  If not, does the uneven distribution display signs of geographic clustering?\n\n3.  If clustering exists, where exactly are these hotspots and lagging zones located?\n\nTwo data sets will be used in this hands-on exercise, they are:\n\n- Hunan province administrative boundary layer at county level. This is a geospatial data set in ESRI shapefile format.\n\n- Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.\n\nThis analysis relies on sf (geospatial data handling), tidyverse (attribute data wrangling), spdep (spatial weights and autocorrelation modeling), and tmap (choropleth mapping). The following initialization code handles environment deployment by auditing your local library for these packages, installing any missing components, and attaching them to the active R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Loading the packages into R environment\npacman::p_load(sf, spdep, tmap, tidyverse, sfdep)\n```\n:::\n\n\n## 5.1.2 Loading data into R environment\n\n### Import shapefile into R environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\")\n```\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\nFirst 10 features:\n     NAME_2  ID_3    NAME_3   ENGTYPE_3 Shape_Leng Shape_Area    County\n1   Changde 21098   Anxiang      County   1.869074 0.10056190   Anxiang\n2   Changde 21100   Hanshou      County   2.360691 0.19978745   Hanshou\n3   Changde 21101    Jinshi County City   1.425620 0.05302413    Jinshi\n4   Changde 21102        Li      County   3.474325 0.18908121        Li\n5   Changde 21103     Linli      County   2.289506 0.11450357     Linli\n6   Changde 21104    Shimen      County   4.171918 0.37194707    Shimen\n7  Changsha 21109   Liuyang County City   4.060579 0.46016789   Liuyang\n8  Changsha 21110 Ningxiang      County   3.323754 0.26614198 Ningxiang\n9  Changsha 21111 Wangcheng      County   2.292093 0.13049161 Wangcheng\n10 Chenzhou 21112     Anren      County   2.240739 0.13343936     Anren\n                         geometry\n1  POLYGON ((112.0625 29.75523...\n2  POLYGON ((112.2288 29.11684...\n3  POLYGON ((111.8927 29.6013,...\n4  POLYGON ((111.3731 29.94649...\n5  POLYGON ((111.6324 29.76288...\n6  POLYGON ((110.8825 30.11675...\n7  POLYGON ((113.9905 28.5682,...\n8  POLYGON ((112.7181 28.38299...\n9  POLYGON ((112.7914 28.52688...\n10 POLYGON ((113.1757 26.82734...\n```\n\n\n:::\n:::\n\n\n### Import csv file into r environment\n\nImport *Hunan_2012.csv* into R by using [`read_csv()`](https://readr.tidyverse.org/reference/read_delim.html) of **readr** package. The output is R data frame class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 88 × 29\n   County    City   avg_wage deposite    FAI Gov_Rev Gov_Exp    GDP GDPPC    GIO\n   <chr>     <chr>     <dbl>    <dbl>  <dbl>   <dbl>   <dbl>  <dbl> <dbl>  <dbl>\n 1 Anhua     Yiyang    30544   10967   6832.    457.   2703  13225  14567  9277.\n 2 Anren     Chenz…    28058    4599.  6386.    221.   1455.  4941. 12761  4189.\n 3 Anxiang   Chang…    31935    5517.  3541     244.   1780. 12482  23667  5109.\n 4 Baojing   Hunan…    30843    2250   1005.    193.   1379.  4088. 14563  3624.\n 5 Chaling   Zhuzh…    31251    8241.  6508.    620.   1947  11585  20078  9158.\n 6 Changning Hengy…    28518   10860   7920     770.   2632. 19886  24418 37392 \n 7 Changsha  Chang…    54540   24332  33624    5350    7886. 88009  88656 51361 \n 8 Chengbu   Shaoy…    28597    2581.  1922.    161.   1192.  2570. 10132  1681.\n 9 Chenxi    Huaih…    33580    4990   5818.    460.   1724.  7755. 17026  6644.\n10 Cili      Zhang…    33099    8117.  4498.    500.   2306. 11378  18714  5843.\n# ℹ 78 more rows\n# ℹ 19 more variables: Loan <dbl>, NIPCR <dbl>, Bed <dbl>, Emp <dbl>,\n#   EmpR <dbl>, EmpRT <dbl>, Pri_Stu <dbl>, Sec_Stu <dbl>, Household <dbl>,\n#   Household_R <dbl>, NOIP <dbl>, Pop_R <dbl>, RSCG <dbl>, Pop_T <dbl>,\n#   Agri <dbl>, Service <dbl>, Disp_Inc <dbl>, RORP <dbl>, ROREmp <dbl>\n```\n\n\n:::\n:::\n\n\n### Performing relational join the data\n\nUsing [`left_join()`](https://dplyr.tidyverse.org/reference/mutate-joins.html) of **dplyr** update the attribute table of *hunan*’s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe.\n\nThese data fields will be selected for analysis: **NAME_2**, **ID_3**, **NAME_3**, **ENGTYPE_3**, **Country**, **GDPPC** and **geometry**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\n### Visualising Regional Development Indicator\n\nUsing `qtm()` of **tmap** package to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-8-1.png){width=1536}\n:::\n:::\n\n\n::: callout-note\nIn `tmap` (specifically within functions like `tm_polygons()` or `tm_fill()`), the `style` parameter controls the **data classification method** used to split your continuous development data into discrete color bins.\n\nThe core difference between **`style = \"equal\"`** (Equal Interval) and **`style = \"quantile\"`** (Quantile) lies in how they calculate the range of each bin versus how many map features end up in each bin.\n\nHere is the direct comparison:\n\n| **Classification Style** | **How It Works** | **Map Visual Effect** | **Best Used For** |\n|------------------|------------------|------------------|------------------|\n| **`\"equal\"`** *(Equal Interval)* | Divides the **total data range** (Max - Min) into equal-sized value intervals. | Emphasizes absolute differences and **extremes / outliers** (e.g., one ultra-rich city might get its own color category). | Data that is already **evenly spread out** or when you want to highlight absolute thresholds. |\n| **`\"quantile\"`** *(Quantile)* | Distributes an **equal number of geographic features** (polygons) into each bin. | Results in a **balanced, high-contrast map** where every color is equally represented. | Data that is **highly skewed** (e.g., wealth distribution) or when you want to look at relative rankings (e.g., top 20% vs bottom 20%). |\n:::\n\n## 5.1.3 Global Measures of Spatial Autocorrelation\n\n### Computing Contiguity Spatial Weights\n\nComputing global spatial autocorrelation requires a spatial weights matrix to formalize neighborhood connections across the study area's counties. The code below uses *spdep::poly2nb()* to build a contiguity-based neighbor list from regional boundaries. By default, the queen argument is set to TRUE, meaning the function identifies first-order neighbors sharing any boundary segment or vertex. Setting *queen = FALSE* limits the definition to regions sharing a contiguous linear border (Rook contiguity).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\nThe summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbours, and the most connected region (85) with 11 neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=FALSE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 10 \n 2  2 12 20 21 14 11  3  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 10 links\n```\n\n\n:::\n:::\n\n\n### Row-standardised weights matrix\n\nThe next step involves assigning weights to the neighbor structures using a row-standardized approach (style = \"W\"). This method assigns an equal fractional weight (1/ number of neighbors) to each adjacent county, allowing the spatial lag to represent the local average. A known limitation of row-standardization is its vulnerability to edge effects; administrative units on the periphery of the study area have fewer neighboring connections, potentially skewing the calculated spatial autocorrelation. While this example implements style = \"W\" for baseline interpretation, more robust configurations, such as basic binary weights (style = \"B\"), are available to address these geographic boundary limits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 38.46432 365.9186\n```\n\n\n:::\n:::\n\n\n## 5.1.4 Global Measures of Spatial Autocorrelation: Moran’s I\n\n### Maron’s I test\n\n::: callout-note\nGlobal Moran’s I is the foundational and most widely used metric for quantifying global spatial autocorrelation. It measures the overall degree to which similar values of a variable cluster together, disperse, or distribute randomly across a defined geographic space.\n\nIt is the spatial equivalent of Pearson's correlation coefficient, mathematically translating Tobler’s First Law of Geography: \"Everything is related to everything else, but near things are more related than distant things.\"\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.8103, p-value = 7.535e-07\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.308366499      -0.011494253       0.004421564 \n```\n\n\n:::\n:::\n\n\nThe statistical conclusion is that you reject the null hypothesis of complete spatial randomness at a $>99.9\\%$ confidence level ($p < 0.001$).\n\nBecause the p-value ($1.095 \\times 10^{-6}$) is substantially smaller than the standard alpha level of 0.05, and the Z-score (standard deviate) is 4.7351, the results are highly statistically significant. It can be concluded in favor of the alternative hypothesis: the data exhibits significant positive spatial autocorrelation.\n\nBased on this output, there is highly significant positive spatial autocorrelation in the GDP per capita (GDPPC) across the measured regions in Hunan.\n\nThe data strongly rejects the null hypothesis of Complete Spatial Randomness (CSR) in favor of the alternative hypothesis that the values are spatially clustered.\n\nStatistically, this confirms that the observed clustering of similar GDPPC values (Moran's I of 0.3007) is not due to random chance.\n\n### Computing Monte Carlo Moran’s I\n\n::: callout-note\n**Monte Carlo Moran’s I** is a simulation-based (permutation) method used to determine the statistical significance of the Moran’s I statistic.\n\nInstead of relying on standard analytical formulas—which often assume your underlying data follows a normal distribution—the Monte Carlo approach uses brute-force computation to build an empirical \"null distribution\" specific to your exact dataset and spatial weights.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30837, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nThe statistical conclusion is that you **reject the null hypothesis of Complete Spatial Randomness** at a 99.9% confidence level ($p = 0.001$).\n\nBecause the p-value (0.001) is strictly less than the standard significance levels (such as 0.05 or 0.01), the result is highly statistically significant. You conclude that the data exhibits **significant positive spatial autocorrelation**.\n\nHere is what the specific Monte Carlo metrics reveal about your data:\n\n- **Observed Rank = 1000:** The simulation shuffled your GDPPC data across the map 999 times. Your actual observed Moran's I statistic (0.30837) ranked 1000th out of the 1000 total iterations (999 random + 1 observed). This means your actual data was more spatially clustered than *every single one* of the 999 random permutations.\n\n- **P-value = 0.001:** This is the absolute minimum possible p-value when running 999 simulations. It is calculated by taking the number of instances equal to or more extreme than your observation (which is just 1—your actual observation) and dividing it by the total iterations (1000).\n\nThis non-parametric test strongly confirms the findings of your previous analytical test: the geographic clustering of high-GDP and low-GDP counties in Hunan province is genuine and practically impossible to generate by random geographic chance.\n\n### Visualising Monte Carlo Moran’s I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01501115\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004431934\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18588 -0.06228 -0.02137 -0.01501  0.02677  0.27294 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n**Plotting using ggplot2 package**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# ggplot2 requires data to be in a data frame\nggplot(data.frame(Simulated_I = bperm$res), aes(x = Simulated_I)) +\n  geom_histogram(bins = 20, color = \"black\", fill = \"lightgray\") +\n  geom_vline(xintercept = 0, color = \"red\") +\n  labs(x = \"Simulated Moran's I\", \n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n# 5.2 Local Measures of Spatial Autocorrelation\n\n## 5.2.1 Overview\n\nUnlike global spatial statistics that provide a single summary score for an entire map, Local Measures of Spatial Autocorrelation (LMSA) calculate a unique score for *every individual location* based on its immediate neighbors. This allows you to pinpoint the exact locations of clusters and outliers hidden within your map.\n\nThe two main local methods are:\n\n- **LISA (Local Indicators of Spatial Association):** These mathematically break down global statistics into local scores to find specific clusters and spatial outliers.\n\n- **Getis-Ord’s Gi-statistics:** An alternative method specifically designed to highlight geographic hot spots and cold spots.\n\nIn this exercise, you will use the `sfdep` package in R to run these local calculations. By the end, you will be able to:\n\n- Import spatial boundaries using `sf` and tabular CSV data using `readr`.\n\n- Merge the datasets together using `dplyr`.\n\n- Calculate LISA to detect local clusters and outliers.\n\n- Calculate Getis-Ord’s Gi-statistics to identify hot and cold spots.\n\n- Visualize your results on a map using `tmap`.\n\n## 5.2.2 Setting\n\n**Analytical question**\n\nA primary goal for local governments and urban planners is ensuring that economic development is distributed equally across a region. This study uses spatial statistics to test whether that goal is being met by asking three progressive questions:\n\n1.  Is economic development evenly distributed geographically?\n\n2.  If not, are there signs of spatial clustering?\n\n3.  If clusters do exist, exactly where are they located?\n\nTo answer these questions, this case study examines the geographic distribution of a specific economic indicator—GDP per capita—across Hunan Province, China.\n\n**Visulisation the data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Quantile interval classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-19-1.png){width=1344}\n:::\n:::\n\n\n## 5.2.3 Local Indicators of Spatial Association (LISA)\n\nThis session will show you how to apply LISA, especially local Moran'I to detect cluster and/or outlier from GDP per Capita 2012 of Hunan Province, China.\n\n### Computing contiguity spatial weights\n\nBefore we can compute the local spatial autocorrelation statistics, we need to construct a spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\n::: callout-note\n[`st_contiguity()`](https://sfdep.josiahparry.com/reference/st_contiguity) of **sfdep** package is used to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. If you look at the documentation you will see that you can pass a “queen” argument that takes TRUE or FALSE as options. If you do not specify this argument the default is set to TRUE, that is, if you don’t specify queen = FALSE this function will return a list of first order neighbours using the Queen criteria.\n\nNext, [`st_weights()`](https://sfdep.josiahparry.com/reference/st_weights) is used to calculate polygon spatial weights from the *nb* list.\n\n`st_weights()` provides three arguments, they are:\n\n- nb: A neighbor list object as created by `st_neighbors()`.\n\n- style: Default “W” for row standardized weights. This value can also be “B”, “C”, “U”, “minmax”, and “S”. B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n\n- allow_zero: If TRUE, assigns zero as lagged value to zone without neighbors.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(\n           nb, style = \"W\"),\n         .before = 1) \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(wm_q$nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n### Row-standardised weights matrix\n\nwe need to assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight (style=“W”). This is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values. While this is the most intuitive way to summaries the neighbors’ values it has one drawback in that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data. For this example, we’ll stick with the style=“W” option for simplicity’s sake but note that other more robust options are available, notably style=“B”.\n\n::: callout-note\n- The input of [`nb2listw()`](https://r-spatial.github.io/spdep/reference/nb2listw.html) must be an object of class **nb**. The syntax of the function has two major arguments, namely style and zero.poly.\n\n- *style* can take values “W”, “B”, “C”, “U”, “minmax” and “S”. B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n\n- If *zero policy* is set to TRUE, weights vectors of zero length are inserted for regions without neighbour in the neighbours list. These will in turn generate lag values of zero, equivalent to the sum of products of the zero row t(rep(0, length=length(neighbours))) %\\*% x, for arbitrary numerical vector x of length length(neighbours). The spatially lagged value of x for the zero-neighbour region will then be zero, which may (or may not) be a sensible choice.\n:::\n\n### Computing local Moran's I\n\nThe [`local_moran()`](https://sfdep.josiahparry.com/reference/local_moran) function of **sfdep** will be used. It computes *Ii* values, given a set of *zi* values and a listw object providing neighbour weighting information for the polygon associated with the zi values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nlisa <- wm_q %>% \n  mutate(local_moran = local_moran(\n    GDPPC, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 21\n$ ii           <dbl> -1.468468e-03, 2.587817e-02, -1.198765e-02, 1.022468e-03,…\n$ eii          <dbl> 1.472724e-03, -1.337157e-02, 2.542108e-03, -9.522978e-05,…\n$ var_ii       <dbl> 5.187992e-04, 1.413972e-02, 1.109689e-01, 4.768012e-06, 1…\n$ z_ii         <dbl> -0.12912898, 0.33007787, -0.04361717, 0.51186518, 0.33919…\n$ p_ii         <dbl> 8.972556e-01, 7.413411e-01, 9.652096e-01, 6.087454e-01, 7…\n$ p_ii_sim     <dbl> 0.80, 0.98, 0.92, 0.56, 0.58, 0.86, 0.06, 0.12, 0.02, 0.2…\n$ p_folded_sim <dbl> 0.40, 0.49, 0.46, 0.28, 0.29, 0.43, 0.03, 0.06, 0.01, 0.1…\n$ skewness     <dbl> -1.0560692, -1.0439328, 0.8429629, 0.8423923, 1.3810032, …\n$ kurtosis     <dbl> 1.31492710, 0.76654076, 0.12251048, 0.37514702, 2.3883407…\n$ mean         <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ median       <fct> High-High, High-High, High-High, High-High, High-High, Hi…\n$ pysal        <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ nb           <nb> <2, 3, 4, 57, 85>, <1, 57, 58, 78, 85>, <1, 4, 5, 85>, <1,…\n$ wt           <list> <0.2, 0.2, 0.2, 0.2, 0.2>, <0.2, 0.2, 0.2, 0.2, 0.2>, <0…\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [°]> POLYGON ((112.0625 29.75523..., POLYGON ((112.228…\n```\n\n\n:::\n:::\n\n\n**Mapping the local Moran's I value**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\ntm_polygons(fill = \"ii\",\n            fill.scale = tm_scale_intervals(\n              style = \"pretty\",\n              n = 5,\n              values = \"brewer.RdBu\"),\n            fill.legend = tm_legend(\n              title = \"Local Morans'I\",\n              position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Loal Morans'I of GDPPC (Queen's method)\", size = 2.5)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n**Mapping local Moran's I p-values**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n                position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Loal Moran's I of GDPPC (Queen's method)\", size = 2.5)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-25-1.png){width=960}\n:::\n:::\n\n\n**Mapping both local Moran's I values and p-values**\n\n\n::: {.cell fig-heigh='10'}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Loal Moran's I of GDPPC (Queen's method)\", size = 2)\n\np_ii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n                position = tm_pos_in(\"left\", \"bottom\")\n              )) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Loal Moran's I of GDPPC (Queen's method)\", size = 2)\n\ntmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-26-1.png){width=1344}\n:::\n:::\n\n\n### Preparing and Visualising LISA map\n\nVisualizing LISA involves creating maps that highlight significant spatial patterns, such as hot spots (high values clustered together) and cold spots (low values clustered together), as well as identifying spatial outliers. Common methods include choropleth maps showing LISA values, Moran scatterplots which depict local spatial autocorrelation for individual locations, and hot spot analysis maps.\n\nThe LISA Cluster Map shows the significant locations color coded by type of spatial autocorrelation. The first step before we can generate the LISA cluster map is to plot the Moran scatterplot.\n\n**Plotting Moran scatterplot**\n\nA Moran Scatterplot is a graphical tool in spatial analysis that visualizes the relationship between a variable’s values and the average values of its neighboring locations (its spatial lag) to identify spatial autocorrelation. By plotting standardized values of the variable on the x-axis and its spatial lag on the y-axis, the plot’s slope represents Moran’s I, revealing patterns of high-high or low-low value clusters and high-low or low-high value outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(lag_GDPPC = st_lag(\n    GDPPC, nb, wt),\n    .before = 1) %>%\n  unnest(lag_GDPPC)\n```\n:::\n\n\nUsing ggplot to plot the Moran Scatterplot of GDPPC against it spatial lag version\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"red\") +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\nUpgrade the plot with LISA quadrants\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$lag_GDPPC), lty=2) + \n  geom_vline(xintercept=mean(lisa$GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\n**Plotting Moran scatterplot with standardised variable**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(z_GDPPC = scale(GDPPC),\n         z_lag_GDPPC = scale(lag_GDPPC),\n         .before = 1)\n```\n:::\n\n\nplot the Moran scatterplot again\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = z_GDPPC, \n           y = z_lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$z_lag_GDPPC), lty=2) + \n  geom_vline(xintercept=mean(lisa$z_GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised GDPPC\",\n       y = \"Standardised Spatial Lag of GDPPC\",\n       title = \"Standardised Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n\n**Preparing LISA map classes**\n\nDerives the spatially lagged variable of interest and centers the spatially lagged variable around its mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05       \n```\n:::\n\n\n**Plotting and visualising LISA map**\n\n::: callout-note\nBy default, the LISA classes are stored in *mean*, *median* and *pysal* fields of lisa sf data frame. To prepare the LISA map, we will derive a new field called LISA-cluster from either one of these three fields\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(\n    LISA_cluster = ifelse(\n      p_ii < 0.05,\n      as.character(mean), \n      \"Insignificant\"),\n    LISA_cluster = factor(\n      LISA_cluster,\n      levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")\n    )\n  )\n```\n:::\n\n\n::: callout-note\na new class called *Insignificant* has been added for the records where by p_ii \\> 0.05.\n:::\n\nPlot LISA map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_map <- tm_shape(lisa) + \n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\", size = 3)\nlisa_map\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-34-1.png){width=960}\n:::\n:::\n\n\nFor effective interpretation, it is better to plot both the local Moran’s I values map and its corresponding p-values map next to each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Loal Moran's I of GDPPC (Queen's method)\", size = 2)\n\nlisa_map <- tm_shape(lisa) + \n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\", size = 2)\nlisa_map\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-35-1.png){width=1344}\n:::\n\n```{.r .cell-code}\ntmap_arrange(ii.map, lisa_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-35-2.png){width=1344}\n:::\n:::\n\n\n## 5.2.4 Hot Spots and Cold Spots Analysis (HCSA)\n\n**Hot Spot and Cold Spot Analysis (HCSA)** uses spatial statistics to identify statistically significant clusters within geographic data.\n\n- **Hot Spots:** Areas where high values are concentrated and surrounded by other high values.\n\n- **Cold Spots:** Areas where low values are concentrated and surrounded by other low values.\n\nUsing methods like the **Getis-Ord Gi\\* statistic**, HCSA determines if these patterns (such as regional clusters of high or low GDP per capita) are statistically significant or merely random noise.\n\nThe analysis involves four steps:\n\n1.  Deriving a spatial weight matrix.\n\n2.  Computing Gi\\* statistics.\n\n3.  Mapping the Gi\\* statistics.\n\n4.  Communicating the results.\n\n### Deriving distance weight matrix\n\nWhist the spatial autocorrelation considered units which shared borders, for Getis-Ord Gi\\* statistics, we are defining neighbours based on distance.\n\nThere are two type of distance-based proximity matrix, they are:\n\n- fixed distance weight matrix,\n\n- adaptive distance weight matrix, and\n\n- inverse distance weights.\n\n**Computing fixed distance weights**\n\nIn this section, you will learn how to compute fixed distance weight matrix by using `st_dist_band()` and `st_weights()` of sfdep package.\n\nFirstly, we need to determine the upper limit for distance band\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- critical_threshold(st_geometry(hunan))\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62.82614\n```\n\n\n:::\n:::\n\n\nThe summary report shows that the largest first nearest neighbour distance is 62.83 km, so using this as the upper threshold gives certainty that all units will have at least one neighbour.\n\nCompute the fixed distance weight based on the threshold value computed above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_fdw <- hunan %>% \n  mutate(nb = include_self(\n    st_dist_band(\n      st_geometry(geometry), \n      upper = ct)),\n    wt = st_weights(nb, \n                    style = \"W\"),\n    .before = 1) \n```\n:::\n\n\n**Computing adaptive distance weights**\n\nOne of the characteristics of fixed distance weight matrix is that more densely settled areas (usually the urban areas) tend to have more neighbours and the less densely settled areas (usually the rural counties) tend to have lesser neighbours. Having many neighbours smooth the neighbour relationship across more neighbours.\n\nIt is possible to control the numbers of neighbours directly using k-nearest neighbours, either accepting asymmetric neighbours or imposing symmetry as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_adw <- hunan %>%\n  mutate(nb = include_self(\n    st_knn(\n      st_geometry(geometry),\n      k = 6)),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1)\n```\n:::\n\n\n### Computing local Gi\\*\n\nLocal Gi\\* (pronounced “G-i-star”) is a Getis-Ord statistic used in spatial analysis to identify statistically significant hot spots and cold spots of high or low attribute values within a dataset. It measures the spatial clustering of values by comparing the total value within a specified neighborhood to the global total, producing a Z-score and p-value for each location to determine the likelihood that the observed pattern is not due to random chance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- hunan_fdw %>%\n  mutate(\n    gistar = local_gstar_perm(\n      GDPPC, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gistar)\n```\n:::\n\n\n### Preparing and Visualising HCSA Map\n\n**Mapping Gi\\* with fix distance weights**\n\nThematic mapping functions of tmaps are used to prepare a choropleth map showing the distribution of Gi\\* values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 6,\n                values = \"brewer.rd_bu\"),\n              fill.legend = tm_legend(\n                title = \"Gi*\",\n                position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Gi* of GDPPC (Fixed Bandwidth d = 60799.91m)\", size = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-40-1.png){width=960}\n:::\n:::\n\n\n**Mapping local Gi\\* p-values**\n\nThe choropleth shows there is evidence for both positive and negative Ii values. However, it is useful to consider the p-values for each of these values, as consider above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"simulated p-value\",\n                position = tm_pos_out())) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of local Gi* of GDPPC (Fixed distance)\", size = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-41-1.png){width=960}\n:::\n:::\n\n\n**Mapping both Gi\\* values and p-values**\n\nFor effective interpretation, it is better to plot both the Gi\\* values map and its corresponding p-values map next to each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGi_star_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"-brewer.rd_bu\"),\n              fill.legend = tm_legend(\n                title = \"local Gi*\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Gi* of GDPPC\", size =2)\n\np_values_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n                position = tm_pos_in(\"left\", \"bottom\")\n              )) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of local Gi* of GDPPC (fixed distance)\", size =2)\n\ntmap_arrange(Gi_star_map, p_values_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-42-1.png){width=1344}\n:::\n:::\n\n\n**Plotting and visualising HCSA Map**\n\nBy default, the HCSA classes are stored in *cluster* field of *HCSA_fdw* sf data frame. To prepare the HSCA map, we will derive a new field called *HCSA_cluster* from *cluster* field\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- HCSA_fdw %>%\n  mutate(HCSA_cluster = case_when(\n    p_sim > 0.05 ~ \"Insignificant\",\n    p_sim <= 0.05 & cluster == \"High\" ~ \"Hot spot\",\n    p_sim <= 0.05 & cluster == \"Low\"  ~ \"Cold spot\",\n    TRUE ~ \"Other\"),\n    HCSA_cluster = factor(\n      HCSA_cluster,\n      levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")\n    ),\n    .before = 1\n  )\n```\n:::\n\n\nNow, we can plot the HCSA map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_map <- tm_shape(HCSA_fdw) + \n  tm_polygons(\n    fill = \"HCSA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"red\",        # Low-Low\n        \"blue\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"HSCA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"HCSA Clusters (p < 0.05)\", size = 2)\nHCSA_map\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-44-1.png){width=768}\n:::\n:::\n\n\nplot both the local Gi\\* values map and its corresponding HCSA map next to each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(Gi_star_map, HCSA_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-45-1.png){width=1344}\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_Ex05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}